// Sicherheitsnetz fuer Text, den das Modell geschrieben hat.
//
// Der Systemprompt sagt Atlas, dass er richtiges Deutsch schreiben soll, aber
// er faellt zurueck: im Kontext stehen ueberall ASCII-Werkzeugnamen
// (aufgabe_aendern), Statuswerte ("ueberfaellig") und Routen (/faecher), und
// den Stil uebernimmt er dann. Diese Funktion setzt die Umlaute hinterher
// wieder ein.
//
// Bewusst eine feste Wortliste statt einer Regel wie "ae wird zu ä": eine
// Regel wuerde "aktuell", "zuerst", "Klasse", "Baseball" oder "Aerodynamik"
// zerstoeren. Nur was hier steht, wird ersetzt.
//
// Nicht angefasst werden Pfade und Bezeichner: "/faecher" und
// "aufgabe_aendern" muessen ihre Schreibweise behalten, sonst zeigt der Bot
// kaputte Links und falsche Werkzeugnamen. Dafuer sorgen die Grenzen im
// Regex -- ein Treffer darf weder an einem "/" noch an einem "_" haengen.

const WOERTER: Record<string, string> = {
  abgewaehltes: "abgewähltes",
  absaetze: "absätze",
  aehnlichkeit: "ähnlichkeit",
  aeltere: "ältere",
  aelteren: "älteren",
  aeltestes: "ältestes",
  aendern: "ändern",
  aendert: "ändert",
  aenderung: "änderung",
  aenderungen: "änderungen",
  antwortlaenge: "antwortlänge",
  arbeitsblaetter: "arbeitsblätter",
  arbeitsblaettern: "arbeitsblättern",
  aufzaehlung: "aufzählung",
  ausdruecklichen: "ausdrücklichen",
  ausfaellt: "ausfällt",
  ausschliesslich: "ausschließlich",
  aussenpolitische: "außenpolitische",
  ausserdem: "außerdem",
  ausserhalb: "außerhalb",
  behaelt: "behält",
  beispielsaetzen: "beispielsätzen",
  beruehrt: "berührt",
  bestaetigen: "bestätigen",
  bestaetigung: "bestätigung",
  blaetter: "blätter",
  blaettern: "blättern",
  bloecke: "blöcke",
  bloecken: "blöcken",
  blossen: "bloßen",
  brueche: "brüche",
  buendelt: "bündelt",
  dafuer: "dafür",
  durchlaesst: "durchlässt",
  eingeschraenkt: "eingeschränkt",
  einschraenken: "einschränken",
  eintraege: "einträge",
  elektronenpaarabstossungsmodell: "elektronenpaarabstoßungsmodell",
  enthaelt: "enthält",
  erhoeht: "erhöht",
  erklaerfragen: "erklärfragen",
  erklaerst: "erklärst",
  erklaert: "erklärt",
  erklaertext: "erklärtext",
  erklaerung: "erklärung",
  erklaerungen: "erklärungen",
  eroerterung: "erörterung",
  faecher: "fächer",
  faecherliste: "fächerliste",
  faechern: "fächern",
  faellig: "fällig",
  faellige: "fällige",
  faelligen: "fälligen",
  faelliges: "fälliges",
  faelligkeit: "fälligkeit",
  faelligkeitsdatum: "fälligkeitsdatum",
  faelligkeitsfach: "fälligkeitsfach",
  faelligkeitstag: "fälligkeitstag",
  faellt: "fällt",
  faerbt: "färbt",
  fliesskommazahl: "fließkommazahl",
  franzoesisch: "französisch",
  frueh: "früh",
  fruehestens: "frühestens",
  fuehren: "führen",
  fuehrt: "führt",
  fuenf: "fünf",
  fuer: "für",
  fuers: "fürs",
  gaengige: "gängige",
  geaendert: "geändert",
  geaenderte: "geänderte",
  gehoert: "gehört",
  gekuerzt: "gekürzt",
  geloescht: "gelöscht",
  geloest: "gelöst",
  geschaetzte: "geschätzte",
  gespraech: "gespräch",
  gespraechen: "gesprächen",
  gewaehlte: "gewählte",
  gewoehnliche: "gewöhnliche",
  gewuenschten: "gewünschten",
  gluecklicher: "glücklicher",
  glueklicher: "glücklicher",
  grammatikuebersicht: "grammatikübersicht",
  groesse: "größe",
  groesser: "größer",
  groessere: "größere",
  gross: "groß",
  grossbuchstabe: "großbuchstabe",
  grossbuchstaben: "großbuchstaben",
  grosse: "große",
  grosszuegig: "großzügig",
  gueltig: "gültig",
  gueltige: "gültige",
  gueltiger: "gültiger",
  gueltiges: "gültiges",
  haelt: "hält",
  haengen: "hängen",
  haengt: "hängt",
  heissen: "heißen",
  heisst: "heißt",
  herausfaellt: "herausfällt",
  herauskaeme: "herauskäme",
  hinzufuegen: "hinzufügen",
  hoechstens: "höchstens",
  kanaelen: "kanälen",
  koennen: "können",
  kuerzel: "kürzel",
  kuerzen: "kürzen",
  kuerzt: "kürzt",
  laedt: "lädt",
  laenger: "länger",
  laengere: "längere",
  laesst: "lässt",
  laeuft: "läuft",
  lernplaene: "lernpläne",
  loeschbar: "löschbar",
  loeschen: "löschen",
  loeschst: "löschst",
  loescht: "löscht",
  loeschwerkzeug: "löschwerkzeug",
  loese: "löse",
  loesen: "lösen",
  loest: "löst",
  loesung: "lösung",
  loesungsweg: "lösungsweg",
  luecken: "lücken",
  maerz: "märz",
  moeglich: "möglich",
  muendlich: "mündlich",
  muendliche: "mündliche",
  muendlichen: "mündlichen",
  musterloesung: "musterlösung",
  naechste: "nächste",
  naechsten: "nächsten",
  naechster: "nächster",
  naechstes: "nächstes",
  naehe: "nähe",
  noetig: "nötig",
  noetige: "nötige",
  oberflaeche: "oberfläche",
  oeffnen: "öffnen",
  oekologie: "ökologie",
  oekosystem: "ökosystem",
  oekosystems: "ökosystems",
  oel: "öl",
  praefix: "präfix",
  praezise: "präzise",
  pruef: "prüf",
  pruefen: "prüfen",
  pruefung: "prüfung",
  pruefungen: "prüfungen",
  pruefungs: "prüfungs",
  pruefungshinweis: "prüfungshinweis",
  pruefungskarte: "prüfungskarte",
  pruefungstypen: "prüfungstypen",
  pruefungsvorbereitung: "prüfungsvorbereitung",
  rueckgaengig: "rückgängig",
  ruecklaeufig: "rückläufig",
  saetze: "sätze",
  schlaegt: "schlägt",
  schliessen: "schließen",
  schliesst: "schließt",
  schraenkt: "schränkt",
  schueler: "schüler",
  schuelers: "schülers",
  schuetzt: "schützt",
  schwaechste: "schwächste",
  schwaechsten: "schwächsten",
  spaet: "spät",
  spaete: "späte",
  spaeter: "später",
  spaeteres: "späteres",
  staerker: "stärker",
  staerkstem: "stärkstem",
  stuerzt: "stürzt",
  tagsueber: "tagsüber",
  textaenderung: "textänderung",
  traegst: "trägst",
  traegt: "trägt",
  ueben: "üben",
  ueber: "über",
  uebereinstimmung: "übereinstimmung",
  ueberfaellig: "überfällig",
  ueberfaellige: "überfällige",
  ueberfaelliges: "überfälliges",
  uebergeben: "übergeben",
  uebergebenen: "übergebenen",
  ueberhaupt: "überhaupt",
  ueberlappung: "überlappung",
  ueberlebt: "überlebt",
  ueberlege: "überlege",
  ueberlegungen: "überlegungen",
  uebermorgen: "übermorgen",
  uebernimm: "übernimm",
  uebernimmt: "übernimmt",
  ueberschrift: "überschrift",
  ueberschriften: "überschriften",
  uebersetzt: "übersetzt",
  uebersicht: "übersicht",
  ueberspringt: "überspringt",
  uebersprungen: "übersprungen",
  ueberwachtes: "überwachtes",
  uebung: "übung",
  uebungsaufgabe: "übungsaufgabe",
  uebungsaufgaben: "übungsaufgaben",
  unabhaengig: "unabhängig",
  ungueltig: "ungültig",
  ungueltige: "ungültige",
  ungueltigem: "ungültigem",
  ungueltiger: "ungültiger",
  ungueltiges: "ungültiges",
  unmoegliches: "unmögliches",
  unterstuetzt: "unterstützt",
  unveraendert: "unverändert",
  unvollstaendige: "unvollständige",
  unvollstaendigen: "unvollständigen",
  verfuegbar: "verfügbar",
  verhaelt: "verhält",
  vollstaendig: "vollständig",
  vollstaendige: "vollständige",
  vollstaendigen: "vollständigen",
  vorschlaege: "vorschläge",
  vorschlaegst: "vorschlägst",
  waehlen: "wählen",
  waehrend: "während",
  waere: "wäre",
  waeren: "wären",
  weiss: "weiß",
  woerter: "wörter",
  woertern: "wörtern",
  wortzwischenraeumen: "wortzwischenräumen",
  wuerde: "würde",
  wuerden: "würden",
  zaehlen: "zählen",
  zaehlt: "zählt",
  zehntklaesslers: "zehntklässlers",
  zuege: "züge",
  zurueck: "zurück",
  zurueckgegeben: "zurückgegeben",
  zurueckgerollt: "zurückgerollt",
  zusaetzlich: "zusätzlich",
  zusaetzliche: "zusätzliche",
  zusammenhaengen: "zusammenhängen",
  ähnlichkeit: "ähnlichkeit",
};

// Ein Wort, das nicht Teil eines Pfades (/faecher) oder eines Bezeichners
// (aufgabe_aendern, faelligTeil, datei.pruefung) ist. Punkt und Bindestrich
// sperren nur dann, wenn direkt ein Wortzeichen anschliesst -- sonst waere
// schon der Satzpunkt in "ist faellig." eine Sperre.
const GRENZE_VORNE = "(?<![\\w/_])(?<!\\w[.-])";
const GRENZE_HINTEN = "(?![\\w/_])(?![.-]\\w)";

function grossform(w: string): string {
  return w[0].toUpperCase() + w.slice(1);
}

const REGELN: Array<[RegExp, string]> = [];
for (const [ascii, richtig] of Object.entries(WOERTER)) {
  REGELN.push([new RegExp(GRENZE_VORNE + ascii + GRENZE_HINTEN, "g"), richtig]);
  REGELN.push([
    new RegExp(GRENZE_VORNE + grossform(ascii) + GRENZE_HINTEN, "g"),
    grossform(richtig),
  ]);
}

export function mitUmlauten(text: string): string {
  let out = text;
  for (const [re, richtig] of REGELN) out = out.replace(re, richtig);
  return out;
}
